package com.example.mobile

data class GaitMotionMode(
    val key: String,
    val name: String,
    val description: String,
    val extT0: Double,
    val extTf: Double,
    val extP: Double,
    val extTmax: Double,
    val flexT0: Double,
    val flexTf: Double,
    val flexP: Double,
    val flexTmax: Double,
    val phaseBias: Double,
    val phaseBiasAt0p6: Double,
    val phaseBiasSlope: Double,
    val eventProbThreshold: Double
)

object GaitMotionModes {
    val all: List<GaitMotionMode> = listOf(
        GaitMotionMode(
            key = "walking",
            name = "平地行走",
            description = "适用于平地正常行走",
            extT0 = 0.0,
            extTf = 0.50,
            extP = 0.70,
            extTmax = 5.0,
            flexT0 = 0.55,
            flexTf = 0.95,
            flexP = 0.80,
            flexTmax = 5.0,
            phaseBias = -0.20,
            phaseBiasAt0p6 = -0.20,
            phaseBiasSlope = 1.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "stairs_up",
            name = "上楼梯",
            description = "适用于上楼梯运动",
            extT0 = 0.0,
            extTf = 0.50,
            extP = 0.40,
            extTmax = 5.0,
            flexT0 = 0.55,
            flexTf = 0.85,
            flexP = 0.35,
            flexTmax = 5.0,
            phaseBias = 0.0,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "stairs_down",
            name = "下楼梯",
            description = "适用于下楼梯运动",
            extT0 = 0.0,
            extTf = 0.0,
            extP = 0.0,
            extTmax = 5.0,
            flexT0 = 0.4,
            flexTf = 0.90,
            flexP = 0.2,
            flexTmax = 5.0,
            phaseBias = 0.0,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "test",
            name = "骑车测试模式",
            description = "骑车测试模式（髋角峰值定时，手动启停）",
            extT0 = 0.0,
            extTf = 0.0,
            extP = 0.0,
            extTmax = 5.0,
            flexT0 = 0.0,
            flexTf = 0.50,
            flexP = 0.2,
            flexTmax = 5.0,
            phaseBias = 0.0,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "walking_test",
            name = "步行测试模式",
            description = "步行测试模式（髋角峰值定时，手动启停）",
            extT0 = 0.0,
            extTf = 0.30,
            extP = 0.70,
            extTmax = 5.0,
            flexT0 = 0.50,
            flexTf = 0.80,
            flexP = 0.80,
            flexTmax = 5.0,
            phaseBias = 0.12,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "cycling",
            name = "骑自行车",
            description = "适用于骑自行车运动",
            extT0 = 0.0,
            extTf = 0.0,
            extP = 0.0,
            extTmax = 5.0,
            flexT0 = 0.40,
            flexTf = 0.90,
            flexP = 0.20,
            flexTmax = 5.0,
            phaseBias = 0.06,
            phaseBiasAt0p6 = 0.06,
            phaseBiasSlope = 1.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "uphill",
            name = "上坡行走",
            description = "适用于上坡行走",
            extT0 = 0.0,
            extTf = 0.0,
            extP = 0.0,
            extTmax = 5.0,
            flexT0 = 0.4,
            flexTf = 0.9,
            flexP = 0.2,
            flexTmax = 5.0,
            phaseBias = 0.0,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        ),
        GaitMotionMode(
            key = "downhill",
            name = "下坡行走",
            description = "适用于下坡行走",
            extT0 = 0.0,
            extTf = 0.30,
            extP = 0.70,
            extTmax = 5.0,
            flexT0 = 0.50,
            flexTf = 0.80,
            flexP = 0.80,
            flexTmax = 5.0,
            phaseBias = -0.20,
            phaseBiasAt0p6 = 0.0,
            phaseBiasSlope = 0.0,
            eventProbThreshold = 0.8
        )
    )

    val byKey: Map<String, GaitMotionMode> = all.associateBy { it.key }
}
