
"""Shared constants for gait control modules."""

import math
import os

LEFT_MOTOR_ID = 0x01
RIGHT_MOTOR_ID = 0x02
CAN_INTERFACE = os.environ.get("GAIT_CAN_INTERFACE", "can0")
WORKSPACE_ROOT = os.environ.get("GAIT_WORKSPACE", "/home/zhang/gait_control_ws")

# RS01 私有 CAN 运控协议（说明书第 4 章）。
RS01_MASTER_ID = int(os.environ.get("GAIT_RS01_MASTER_ID", "0xFD"), 0) & 0xFF
RS01_CONTROL_FUNCTION_ID = 0x01
RS01_FEEDBACK_FUNCTION_ID = 0x02
RS01_ENABLE_FUNCTION_ID = 0x03
RS01_STOP_FUNCTION_ID = 0x04
RS01_MECHANICAL_ZERO_FUNCTION_ID = 0x06
RS01_PARAM_READ_FUNCTION_ID = 0x11
RS01_PARAM_WRITE_FUNCTION_ID = 0x12
RS01_ACTIVE_REPORT_FUNCTION_ID = 0x18
RS01_FEEDBACK_FUNCTION_IDS = (
    RS01_FEEDBACK_FUNCTION_ID,
    RS01_ACTIVE_REPORT_FUNCTION_ID,
)
RS01_EP_SCAN_TIME_INDEX = 0x7026
RS01_ACTIVE_REPORT_HZ = int(os.environ.get("GAIT_RS01_REPORT_HZ", "50"))

# 说明书中的量程。
MOTOR_POSITION_MIN = -12.57
MOTOR_POSITION_MAX = 12.57
MOTOR_VELOCITY_MIN = -44.0
MOTOR_VELOCITY_MAX = 44.0
MOTOR_TORQUE_MIN = -17.0
MOTOR_TORQUE_MAX = 17.0
MOTOR_KP_MIN = 0.0
MOTOR_KP_MAX = 500.0
MOTOR_KD_MIN = 0.0
MOTOR_KD_MAX = 5.0

# 兼容旧命名，避免其他模块同步改动过大。
SERVO_STATUS_FUNCTION_ID = RS01_FEEDBACK_FUNCTION_ID
SERVO_START_FUNCTION_ID = RS01_ENABLE_FUNCTION_ID
SERVO_DISABLE_FUNCTION_ID = RS01_STOP_FUNCTION_ID
SERVO_FEEDBACK_CONFIG_FUNCTION_ID = RS01_ACTIVE_REPORT_FUNCTION_ID
MIT_CONTROL_FUNCTION_ID = RS01_CONTROL_FUNCTION_ID
MIT_P_MIN = MOTOR_POSITION_MIN
MIT_P_MAX = MOTOR_POSITION_MAX
MIT_V_MIN = MOTOR_VELOCITY_MIN
MIT_V_MAX = MOTOR_VELOCITY_MAX
MIT_T_MIN = MOTOR_TORQUE_MIN
MIT_T_MAX = MOTOR_TORQUE_MAX
MIT_KP_MIN = MOTOR_KP_MIN
MIT_KP_MAX = MOTOR_KP_MAX
MIT_KD_MIN = MOTOR_KD_MIN
MIT_KD_MAX = MOTOR_KD_MAX

LEFT_MOTOR_SIGN = -1.0
RIGHT_MOTOR_SIGN = 1.0
MOTOR_FEEDBACK_TIMEOUT_SEC = 0.15

AO_CONFIG = {
    # RAO in Li et al. uses raw q = theta_r - theta_l. Keep filter optional.
    "FILTER_ENABLED": False,
    "FILTER_CUTOFF": 0.3,
    "OSC_HARMONICS": 1,
    "OSC_ALPHA0_INIT": 0.0,
    "OSC_ALPHA_INIT": 0.4,
    "OSC_DEN_EPS": 1e-6,
    "OSC_OMEGA_INIT": 2 * math.pi * 1.0,
    "OSC_OMEGA_MIN": 2.5,
    "OSC_OMEGA_MAX": 25.0,
    # RAO dynamic Hebbian gains (Eq.2, Eq.4).
    "RAO_V_PHI": 8.0,
    "RAO_V_W": 3.0,
    "RAO_ETA": 1.5,
    # Zero-crossing frequency correction kw (Eq.5).
    "RAO_XI_W": 12.0,
    "RAO_SIGMA_W": 0.12,
    "RAO_DW": 0.35,
    # Auxiliary phase correction kphi (Eq.8).
    "RAO_XI_PHI": 1.0,
    "RAO_SIGMA_PHI": 0.12,
    "RAO_DPHI": 0.35,
}
